apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: k6-workflow-trigger
  namespace: testkube
spec:
  resource: testworkflow    # Resource type to watch
  resourceSelector:         # Select which resources to watch
    name: basic-k6-workflow
  event: created          # Trigger on modification
  action: run              # Action to take
  execution: testworkflow  # Type of execution
  testSelector:
    name: basic-k6-workflow   # Name of your testworkflow
    namespace: testkube
  disabled: false
