apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: k6-workflow-trigger
  namespace: testkube
spec:
  resource: event
  resourceSelector:
    name: basic-k6-workflow  # Replace with your k6 workflow name
  event: created                 # Changed to trigger on creation
  action: run
  execution: testworkflow
  testSelector:
    name: basic-k6-workflow  # Replace with your k6 workflow name
    namespace: testkube
  disabled: false
