apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: k6-workflow-trigger
  namespace: testkube
spec:
  resource: event
  resourceSelector:
    name: basic-k6-workflow  # Name of your k6 workflow
  event: created                 # Triggers on creation
  action: run                    # Run the workflow
  execution: testworkflow        # Execution type
  testSelector:
    name: basic-k6-workflow  # Same name as above
    namespace: testkube
  disabled: false
